// Mocks generated by Mockito 5.4.6 from annotations
// in ftms/test/features/fit_files/fit_file_detail_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i4;

import 'package:ftms/core/services/fit/fit_file_manager.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [FitFileManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockFitFileManager extends _i1.Mock implements _i2.FitFileManager {
  MockFitFileManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<Map<String, dynamic>?> parseFitFileSessionData(_i4.File? file) =>
      (super.noSuchMethod(
            Invocation.method(#parseFitFileSessionData, [file]),
            returnValue: _i3.Future<Map<String, dynamic>?>.value(),
          )
          as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<List<_i2.FitFileInfo>> getAllFitFilesFromDirectory(
    _i4.Directory? directory,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAllFitFilesFromDirectory, [directory]),
            returnValue: _i3.Future<List<_i2.FitFileInfo>>.value(
              <_i2.FitFileInfo>[],
            ),
          )
          as _i3.Future<List<_i2.FitFileInfo>>);

  @override
  _i3.Future<List<_i2.FitFileInfo>> getAllFitFiles() =>
      (super.noSuchMethod(
            Invocation.method(#getAllFitFiles, []),
            returnValue: _i3.Future<List<_i2.FitFileInfo>>.value(
              <_i2.FitFileInfo>[],
            ),
          )
          as _i3.Future<List<_i2.FitFileInfo>>);

  @override
  _i3.Future<bool> deleteFitFile(String? filePath) =>
      (super.noSuchMethod(
            Invocation.method(#deleteFitFile, [filePath]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<List<String>> deleteFitFiles(List<String>? filePaths) =>
      (super.noSuchMethod(
            Invocation.method(#deleteFitFiles, [filePaths]),
            returnValue: _i3.Future<List<String>>.value(<String>[]),
          )
          as _i3.Future<List<String>>);

  @override
  _i3.Future<int> getFitFileCount() =>
      (super.noSuchMethod(
            Invocation.method(#getFitFileCount, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<int> getTotalFitFileSize() =>
      (super.noSuchMethod(
            Invocation.method(#getTotalFitFileSize, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<_i2.FitFileDetail?> getFitFileDetail(String? filePath) =>
      (super.noSuchMethod(
            Invocation.method(#getFitFileDetail, [filePath]),
            returnValue: _i3.Future<_i2.FitFileDetail?>.value(),
          )
          as _i3.Future<_i2.FitFileDetail?>);
}
