// Mocks generated by Mockito 5.4.6 from annotations
// in ftms/test/features/training/add_training_session_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:ftms/core/config/live_data_display_config.dart' as _i2;
import 'package:ftms/core/config/live_data_field_config.dart' as _i4;
import 'package:ftms/core/models/device_types.dart' as _i3;
import 'package:ftms/features/training/model/training_session.dart' as _i6;
import 'package:ftms/features/training/services/training_session_storage_service.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [LiveDataDisplayConfig].
///
/// See the documentation for Mockito's code generation for more information.
class MockLiveDataDisplayConfig extends _i1.Mock
    implements _i2.LiveDataDisplayConfig {
  MockLiveDataDisplayConfig() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.DeviceType get deviceType =>
      (super.noSuchMethod(
            Invocation.getter(#deviceType),
            returnValue: _i3.DeviceType.indoorBike,
          )
          as _i3.DeviceType);

  @override
  List<_i4.LiveDataFieldConfig> get fields =>
      (super.noSuchMethod(
            Invocation.getter(#fields),
            returnValue: <_i4.LiveDataFieldConfig>[],
          )
          as List<_i4.LiveDataFieldConfig>);

  @override
  bool get availableInDeveloperModeOnly =>
      (super.noSuchMethod(
            Invocation.getter(#availableInDeveloperModeOnly),
            returnValue: false,
          )
          as bool);
}

/// A class which mocks [TrainingSessionStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTrainingSessionStorageService extends _i1.Mock
    implements _i5.TrainingSessionStorageService {
  MockTrainingSessionStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<_i3.DeviceType, List<_i6.TrainingSessionDefinition>>
  get githubSessionsCache =>
      (super.noSuchMethod(
            Invocation.getter(#githubSessionsCache),
            returnValue:
                <_i3.DeviceType, List<_i6.TrainingSessionDefinition>>{},
          )
          as Map<_i3.DeviceType, List<_i6.TrainingSessionDefinition>>);

  @override
  _i7.Future<String> saveSession(_i6.TrainingSessionDefinition? session) =>
      (super.noSuchMethod(
            Invocation.method(#saveSession, [session]),
            returnValue: _i7.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#saveSession, [session]),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<bool> deleteSession(String? title, String? machineType) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSession, [title, machineType]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<List<_i6.TrainingSessionDefinition>> loadTrainingSessions(
    _i3.DeviceType? machineType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#loadTrainingSessions, [machineType]),
            returnValue: _i7.Future<List<_i6.TrainingSessionDefinition>>.value(
              <_i6.TrainingSessionDefinition>[],
            ),
          )
          as _i7.Future<List<_i6.TrainingSessionDefinition>>);
}
