// Mocks generated by Mockito 5.4.6 from annotations
// in ftms/test/features/training/training_session_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:io' as _i13;
import 'dart:typed_data' as _i10;

import 'package:audioplayers/audioplayers.dart' as _i6;
import 'package:flutter/material.dart' as _i15;
import 'package:flutter_blue_plus/flutter_blue_plus.dart' as _i8;
import 'package:flutter_blue_plus_platform_interface/flutter_blue_plus_platform_interface.dart'
    as _i2;
import 'package:flutter_ftms/flutter_ftms.dart' as _i18;
import 'package:ftms/core/models/device_types.dart' as _i17;
import 'package:ftms/core/models/live_data_field_value.dart' as _i12;
import 'package:ftms/core/models/supported_power_range.dart' as _i20;
import 'package:ftms/core/models/supported_resistance_level_range.dart' as _i19;
import 'package:ftms/core/services/devices/bt_device_manager.dart' as _i21;
import 'package:ftms/core/services/devices/ftms.dart' as _i16;
import 'package:ftms/core/services/fit/training_data_recorder.dart' as _i11;
import 'package:ftms/core/services/strava/strava_activity_uploader.dart' as _i5;
import 'package:ftms/core/services/strava/strava_oauth_handler.dart' as _i4;
import 'package:ftms/core/services/strava/strava_service.dart' as _i14;
import 'package:ftms/core/services/strava/strava_token_manager.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDeviceIdentifier_0 extends _i1.SmartFake
    implements _i2.DeviceIdentifier {
  _FakeDeviceIdentifier_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStravaTokenManager_1 extends _i1.SmartFake
    implements _i3.StravaTokenManager {
  _FakeStravaTokenManager_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStravaOAuthHandler_2 extends _i1.SmartFake
    implements _i4.StravaOAuthHandler {
  _FakeStravaOAuthHandler_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStravaActivityUploader_3 extends _i1.SmartFake
    implements _i5.StravaActivityUploader {
  _FakeStravaActivityUploader_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAudioCache_4 extends _i1.SmartFake implements _i6.AudioCache {
  _FakeAudioCache_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCompleter_5<T> extends _i1.SmartFake implements _i7.Completer<T> {
  _FakeCompleter_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BluetoothDevice].
///
/// See the documentation for Mockito's code generation for more information.
class MockBluetoothDevice extends _i1.Mock implements _i8.BluetoothDevice {
  MockBluetoothDevice() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DeviceIdentifier get remoteId =>
      (super.noSuchMethod(
            Invocation.getter(#remoteId),
            returnValue: _FakeDeviceIdentifier_0(
              this,
              Invocation.getter(#remoteId),
            ),
          )
          as _i2.DeviceIdentifier);

  @override
  String get platformName =>
      (super.noSuchMethod(
            Invocation.getter(#platformName),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#platformName),
            ),
          )
          as String);

  @override
  String get advName =>
      (super.noSuchMethod(
            Invocation.getter(#advName),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#advName),
            ),
          )
          as String);

  @override
  List<_i8.BluetoothService> get servicesList =>
      (super.noSuchMethod(
            Invocation.getter(#servicesList),
            returnValue: <_i8.BluetoothService>[],
          )
          as List<_i8.BluetoothService>);

  @override
  bool get isAutoConnectEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#isAutoConnectEnabled),
            returnValue: false,
          )
          as bool);

  @override
  bool get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected), returnValue: false)
          as bool);

  @override
  bool get isDisconnected =>
      (super.noSuchMethod(
            Invocation.getter(#isDisconnected),
            returnValue: false,
          )
          as bool);

  @override
  _i7.Stream<_i8.BluetoothConnectionState> get connectionState =>
      (super.noSuchMethod(
            Invocation.getter(#connectionState),
            returnValue: _i7.Stream<_i8.BluetoothConnectionState>.empty(),
          )
          as _i7.Stream<_i8.BluetoothConnectionState>);

  @override
  int get mtuNow =>
      (super.noSuchMethod(Invocation.getter(#mtuNow), returnValue: 0) as int);

  @override
  _i7.Stream<int> get mtu =>
      (super.noSuchMethod(
            Invocation.getter(#mtu),
            returnValue: _i7.Stream<int>.empty(),
          )
          as _i7.Stream<int>);

  @override
  _i7.Stream<void> get onServicesReset =>
      (super.noSuchMethod(
            Invocation.getter(#onServicesReset),
            returnValue: _i7.Stream<void>.empty(),
          )
          as _i7.Stream<void>);

  @override
  _i7.Stream<_i8.BluetoothBondState> get bondState =>
      (super.noSuchMethod(
            Invocation.getter(#bondState),
            returnValue: _i7.Stream<_i8.BluetoothBondState>.empty(),
          )
          as _i7.Stream<_i8.BluetoothBondState>);

  @override
  _i7.Stream<bool> get isDiscoveringServices =>
      (super.noSuchMethod(
            Invocation.getter(#isDiscoveringServices),
            returnValue: _i7.Stream<bool>.empty(),
          )
          as _i7.Stream<bool>);

  @override
  _i2.DeviceIdentifier get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _FakeDeviceIdentifier_0(this, Invocation.getter(#id)),
          )
          as _i2.DeviceIdentifier);

  @override
  String get localName =>
      (super.noSuchMethod(
            Invocation.getter(#localName),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#localName),
            ),
          )
          as String);

  @override
  String get name =>
      (super.noSuchMethod(
            Invocation.getter(#name),
            returnValue: _i9.dummyValue<String>(this, Invocation.getter(#name)),
          )
          as String);

  @override
  _i7.Stream<_i8.BluetoothConnectionState> get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i7.Stream<_i8.BluetoothConnectionState>.empty(),
          )
          as _i7.Stream<_i8.BluetoothConnectionState>);

  @override
  _i7.Stream<List<_i8.BluetoothService>> get servicesStream =>
      (super.noSuchMethod(
            Invocation.getter(#servicesStream),
            returnValue: _i7.Stream<List<_i8.BluetoothService>>.empty(),
          )
          as _i7.Stream<List<_i8.BluetoothService>>);

  @override
  _i7.Stream<List<_i8.BluetoothService>> get services =>
      (super.noSuchMethod(
            Invocation.getter(#services),
            returnValue: _i7.Stream<List<_i8.BluetoothService>>.empty(),
          )
          as _i7.Stream<List<_i8.BluetoothService>>);

  @override
  void cancelWhenDisconnected(
    _i7.StreamSubscription<dynamic>? subscription, {
    bool? next = false,
    bool? delayed = false,
  }) => super.noSuchMethod(
    Invocation.method(
      #cancelWhenDisconnected,
      [subscription],
      {#next: next, #delayed: delayed},
    ),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> connect({
    required _i8.License? license,
    Duration? timeout = const Duration(seconds: 35),
    int? mtu = 512,
    bool? autoConnect = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#connect, [], {
              #license: license,
              #timeout: timeout,
              #mtu: mtu,
              #autoConnect: autoConnect,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> disconnect({
    int? timeout = 35,
    bool? queue = true,
    int? androidDelay = 2000,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, [], {
              #timeout: timeout,
              #queue: queue,
              #androidDelay: androidDelay,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i8.BluetoothService>> discoverServices({
    bool? subscribeToServicesChanged = true,
    int? timeout = 15,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#discoverServices, [], {
              #subscribeToServicesChanged: subscribeToServicesChanged,
              #timeout: timeout,
            }),
            returnValue: _i7.Future<List<_i8.BluetoothService>>.value(
              <_i8.BluetoothService>[],
            ),
          )
          as _i7.Future<List<_i8.BluetoothService>>);

  @override
  _i7.Future<int> readRssi({int? timeout = 15}) =>
      (super.noSuchMethod(
            Invocation.method(#readRssi, [], {#timeout: timeout}),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<int> requestMtu(
    int? desiredMtu, {
    double? predelay = 0.35,
    int? timeout = 15,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #requestMtu,
              [desiredMtu],
              {#predelay: predelay, #timeout: timeout},
            ),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<void> requestConnectionPriority({
    required _i8.ConnectionPriority? connectionPriorityRequest,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#requestConnectionPriority, [], {
              #connectionPriorityRequest: connectionPriorityRequest,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> setPreferredPhy({
    required int? txPhy,
    required int? rxPhy,
    required _i8.PhyCoding? option,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setPreferredPhy, [], {
              #txPhy: txPhy,
              #rxPhy: rxPhy,
              #option: option,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> createBond({int? timeout = 90, _i10.Uint8List? pin}) =>
      (super.noSuchMethod(
            Invocation.method(#createBond, [], {#timeout: timeout, #pin: pin}),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> removeBond({int? timeout = 30}) =>
      (super.noSuchMethod(
            Invocation.method(#removeBond, [], {#timeout: timeout}),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> clearGattCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearGattCache, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> pair() =>
      (super.noSuchMethod(
            Invocation.method(#pair, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [TrainingDataRecorder].
///
/// See the documentation for Mockito's code generation for more information.
class MockTrainingDataRecorder extends _i1.Mock
    implements _i11.TrainingDataRecorder {
  MockTrainingDataRecorder() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isRecording =>
      (super.noSuchMethod(Invocation.getter(#isRecording), returnValue: false)
          as bool);

  @override
  int get recordCount =>
      (super.noSuchMethod(Invocation.getter(#recordCount), returnValue: 0)
          as int);

  @override
  String get sessionName =>
      (super.noSuchMethod(
            Invocation.getter(#sessionName),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#sessionName),
            ),
          )
          as String);

  @override
  void startRecording() => super.noSuchMethod(
    Invocation.method(#startRecording, []),
    returnValueForMissingStub: null,
  );

  @override
  void stopRecording() => super.noSuchMethod(
    Invocation.method(#stopRecording, []),
    returnValueForMissingStub: null,
  );

  @override
  void recordDataPoint({
    required Map<String, _i12.LiveDataFieldValue>? ftmsParams,
    double? resistanceLevel,
    DateTime? timestamp,
  }) => super.noSuchMethod(
    Invocation.method(#recordDataPoint, [], {
      #ftmsParams: ftmsParams,
      #resistanceLevel: resistanceLevel,
      #timestamp: timestamp,
    }),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<String?> generateFitFile() =>
      (super.noSuchMethod(
            Invocation.method(#generateFitFile, []),
            returnValue: _i7.Future<String?>.value(),
          )
          as _i7.Future<String?>);

  @override
  _i7.Future<String?> generateFitFileToDirectory(
    _i13.Directory? outputDirectory,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#generateFitFileToDirectory, [outputDirectory]),
            returnValue: _i7.Future<String?>.value(),
          )
          as _i7.Future<String?>);

  @override
  Map<String, dynamic> getStatistics() =>
      (super.noSuchMethod(
            Invocation.method(#getStatistics, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}

/// A class which mocks [StravaService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStravaService extends _i1.Mock implements _i14.StravaService {
  MockStravaService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.StravaTokenManager get tokenManager =>
      (super.noSuchMethod(
            Invocation.getter(#tokenManager),
            returnValue: _FakeStravaTokenManager_1(
              this,
              Invocation.getter(#tokenManager),
            ),
          )
          as _i3.StravaTokenManager);

  @override
  _i4.StravaOAuthHandler get oauthHandler =>
      (super.noSuchMethod(
            Invocation.getter(#oauthHandler),
            returnValue: _FakeStravaOAuthHandler_2(
              this,
              Invocation.getter(#oauthHandler),
            ),
          )
          as _i4.StravaOAuthHandler);

  @override
  _i5.StravaActivityUploader get activityUploader =>
      (super.noSuchMethod(
            Invocation.getter(#activityUploader),
            returnValue: _FakeStravaActivityUploader_3(
              this,
              Invocation.getter(#activityUploader),
            ),
          )
          as _i5.StravaActivityUploader);

  @override
  _i7.Future<bool> authenticate({_i15.BuildContext? context}) =>
      (super.noSuchMethod(
            Invocation.method(#authenticate, [], {#context: context}),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> isAuthenticated() =>
      (super.noSuchMethod(
            Invocation.method(#isAuthenticated, []),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<Map<String, dynamic>?> getAuthStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getAuthStatus, []),
            returnValue: _i7.Future<Map<String, dynamic>?>.value(),
          )
          as _i7.Future<Map<String, dynamic>?>);

  @override
  _i7.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<Map<String, dynamic>?> uploadActivity(
    String? fitFilePath,
    String? activityName, {
    String? activityType = 'workout',
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #uploadActivity,
              [fitFilePath, activityName],
              {#activityType: activityType},
            ),
            returnValue: _i7.Future<Map<String, dynamic>?>.value(),
          )
          as _i7.Future<Map<String, dynamic>?>);

  @override
  _i7.Future<Map<String, dynamic>?> uploadActivityWithMetadata({
    required String? fitFilePath,
    required String? name,
    String? description,
    String? activityType = 'workout',
    bool? isPrivate = false,
    bool? hasHeartrate = false,
    bool? hasPower = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadActivityWithMetadata, [], {
              #fitFilePath: fitFilePath,
              #name: name,
              #description: description,
              #activityType: activityType,
              #isPrivate: isPrivate,
              #hasHeartrate: hasHeartrate,
              #hasPower: hasPower,
            }),
            returnValue: _i7.Future<Map<String, dynamic>?>.value(),
          )
          as _i7.Future<Map<String, dynamic>?>);
}

/// A class which mocks [AudioPlayer].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioPlayer extends _i1.Mock implements _i6.AudioPlayer {
  MockAudioPlayer() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.AudioCache get audioCache =>
      (super.noSuchMethod(
            Invocation.getter(#audioCache),
            returnValue: _FakeAudioCache_4(
              this,
              Invocation.getter(#audioCache),
            ),
          )
          as _i6.AudioCache);

  @override
  String get playerId =>
      (super.noSuchMethod(
            Invocation.getter(#playerId),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#playerId),
            ),
          )
          as String);

  @override
  double get volume =>
      (super.noSuchMethod(Invocation.getter(#volume), returnValue: 0.0)
          as double);

  @override
  double get balance =>
      (super.noSuchMethod(Invocation.getter(#balance), returnValue: 0.0)
          as double);

  @override
  double get playbackRate =>
      (super.noSuchMethod(Invocation.getter(#playbackRate), returnValue: 0.0)
          as double);

  @override
  _i6.PlayerMode get mode =>
      (super.noSuchMethod(
            Invocation.getter(#mode),
            returnValue: _i6.PlayerMode.mediaPlayer,
          )
          as _i6.PlayerMode);

  @override
  _i6.ReleaseMode get releaseMode =>
      (super.noSuchMethod(
            Invocation.getter(#releaseMode),
            returnValue: _i6.ReleaseMode.release,
          )
          as _i6.ReleaseMode);

  @override
  _i6.PlayerState get desiredState =>
      (super.noSuchMethod(
            Invocation.getter(#desiredState),
            returnValue: _i6.PlayerState.stopped,
          )
          as _i6.PlayerState);

  @override
  _i6.PlayerState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i6.PlayerState.stopped,
          )
          as _i6.PlayerState);

  @override
  _i7.Completer<void> get creatingCompleter =>
      (super.noSuchMethod(
            Invocation.getter(#creatingCompleter),
            returnValue: _FakeCompleter_5<void>(
              this,
              Invocation.getter(#creatingCompleter),
            ),
          )
          as _i7.Completer<void>);

  @override
  _i7.Stream<_i6.AudioEvent> get eventStream =>
      (super.noSuchMethod(
            Invocation.getter(#eventStream),
            returnValue: _i7.Stream<_i6.AudioEvent>.empty(),
          )
          as _i7.Stream<_i6.AudioEvent>);

  @override
  _i7.Stream<_i6.PlayerState> get onPlayerStateChanged =>
      (super.noSuchMethod(
            Invocation.getter(#onPlayerStateChanged),
            returnValue: _i7.Stream<_i6.PlayerState>.empty(),
          )
          as _i7.Stream<_i6.PlayerState>);

  @override
  _i7.Stream<Duration> get onPositionChanged =>
      (super.noSuchMethod(
            Invocation.getter(#onPositionChanged),
            returnValue: _i7.Stream<Duration>.empty(),
          )
          as _i7.Stream<Duration>);

  @override
  _i7.Stream<Duration> get onDurationChanged =>
      (super.noSuchMethod(
            Invocation.getter(#onDurationChanged),
            returnValue: _i7.Stream<Duration>.empty(),
          )
          as _i7.Stream<Duration>);

  @override
  _i7.Stream<void> get onPlayerComplete =>
      (super.noSuchMethod(
            Invocation.getter(#onPlayerComplete),
            returnValue: _i7.Stream<void>.empty(),
          )
          as _i7.Stream<void>);

  @override
  _i7.Stream<void> get onSeekComplete =>
      (super.noSuchMethod(
            Invocation.getter(#onSeekComplete),
            returnValue: _i7.Stream<void>.empty(),
          )
          as _i7.Stream<void>);

  @override
  _i7.Stream<String> get onLog =>
      (super.noSuchMethod(
            Invocation.getter(#onLog),
            returnValue: _i7.Stream<String>.empty(),
          )
          as _i7.Stream<String>);

  @override
  set audioCache(_i6.AudioCache? value) => super.noSuchMethod(
    Invocation.setter(#audioCache, value),
    returnValueForMissingStub: null,
  );

  @override
  set desiredState(_i6.PlayerState? value) => super.noSuchMethod(
    Invocation.setter(#desiredState, value),
    returnValueForMissingStub: null,
  );

  @override
  set state(_i6.PlayerState? state) => super.noSuchMethod(
    Invocation.setter(#state, state),
    returnValueForMissingStub: null,
  );

  @override
  set positionUpdater(_i6.PositionUpdater? positionUpdater) =>
      super.noSuchMethod(
        Invocation.setter(#positionUpdater, positionUpdater),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> play(
    _i6.Source? source, {
    double? volume,
    double? balance,
    _i6.AudioContext? ctx,
    Duration? position,
    _i6.PlayerMode? mode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #play,
              [source],
              {
                #volume: volume,
                #balance: balance,
                #ctx: ctx,
                #position: position,
                #mode: mode,
              },
            ),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> setAudioContext(_i6.AudioContext? ctx) =>
      (super.noSuchMethod(
            Invocation.method(#setAudioContext, [ctx]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> setPlayerMode(_i6.PlayerMode? mode) =>
      (super.noSuchMethod(
            Invocation.method(#setPlayerMode, [mode]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> pause() =>
      (super.noSuchMethod(
            Invocation.method(#pause, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> resume() =>
      (super.noSuchMethod(
            Invocation.method(#resume, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> release() =>
      (super.noSuchMethod(
            Invocation.method(#release, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> seek(Duration? position) =>
      (super.noSuchMethod(
            Invocation.method(#seek, [position]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> setBalance(double? balance) =>
      (super.noSuchMethod(
            Invocation.method(#setBalance, [balance]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> setVolume(double? volume) =>
      (super.noSuchMethod(
            Invocation.method(#setVolume, [volume]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> setReleaseMode(_i6.ReleaseMode? releaseMode) =>
      (super.noSuchMethod(
            Invocation.method(#setReleaseMode, [releaseMode]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> setPlaybackRate(double? playbackRate) =>
      (super.noSuchMethod(
            Invocation.method(#setPlaybackRate, [playbackRate]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> setSource(_i6.Source? source) =>
      (super.noSuchMethod(
            Invocation.method(#setSource, [source]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> setSourceUrl(String? url, {String? mimeType}) =>
      (super.noSuchMethod(
            Invocation.method(#setSourceUrl, [url], {#mimeType: mimeType}),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> setSourceDeviceFile(String? path, {String? mimeType}) =>
      (super.noSuchMethod(
            Invocation.method(
              #setSourceDeviceFile,
              [path],
              {#mimeType: mimeType},
            ),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> setSourceAsset(String? path, {String? mimeType}) =>
      (super.noSuchMethod(
            Invocation.method(#setSourceAsset, [path], {#mimeType: mimeType}),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> setSourceBytes(_i10.Uint8List? bytes, {String? mimeType}) =>
      (super.noSuchMethod(
            Invocation.method(#setSourceBytes, [bytes], {#mimeType: mimeType}),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<Duration?> getDuration() =>
      (super.noSuchMethod(
            Invocation.method(#getDuration, []),
            returnValue: _i7.Future<Duration?>.value(),
          )
          as _i7.Future<Duration?>);

  @override
  _i7.Future<Duration?> getCurrentPosition() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentPosition, []),
            returnValue: _i7.Future<Duration?>.value(),
          )
          as _i7.Future<Duration?>);

  @override
  _i7.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [Ftms].
///
/// See the documentation for Mockito's code generation for more information.
class MockFtms extends _i1.Mock implements _i16.Ftms {
  MockFtms() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get deviceTypeName =>
      (super.noSuchMethod(
            Invocation.getter(#deviceTypeName),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#deviceTypeName),
            ),
          )
          as String);

  @override
  int get listPriority =>
      (super.noSuchMethod(Invocation.getter(#listPriority), returnValue: 0)
          as int);

  @override
  _i7.Stream<_i17.DeviceType> get deviceTypeStream =>
      (super.noSuchMethod(
            Invocation.getter(#deviceTypeStream),
            returnValue: _i7.Stream<_i17.DeviceType>.empty(),
          )
          as _i7.Stream<_i17.DeviceType>);

  @override
  _i8.BluetoothConnectionState get connectionState =>
      (super.noSuchMethod(
            Invocation.getter(#connectionState),
            returnValue: _i8.BluetoothConnectionState.disconnected,
          )
          as _i8.BluetoothConnectionState);

  @override
  String get name =>
      (super.noSuchMethod(
            Invocation.getter(#name),
            returnValue: _i9.dummyValue<String>(this, Invocation.getter(#name)),
          )
          as String);

  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i9.dummyValue<String>(this, Invocation.getter(#id)),
          )
          as String);

  @override
  bool get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected), returnValue: false)
          as bool);

  @override
  _i7.Future<void> writeCommand(
    _i18.MachineControlPointOpcodeType? opcodeType, {
    int? resistanceLevel,
    int? power,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #writeCommand,
              [opcodeType],
              {#resistanceLevel: resistanceLevel, #power: power},
            ),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> setPowerWithControl(dynamic power) =>
      (super.noSuchMethod(
            Invocation.method(#setPowerWithControl, [power]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> setResistanceWithControl(
    int? resistance, {
    bool? convertFromDefaultRange = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #setResistanceWithControl,
              [resistance],
              {#convertFromDefaultRange: convertFromDefaultRange},
            ),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> stopOrPauseWithControl() =>
      (super.noSuchMethod(
            Invocation.method(#stopOrPauseWithControl, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> startOrResumeWithControl() =>
      (super.noSuchMethod(
            Invocation.method(#startOrResumeWithControl, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> resetWithControl() =>
      (super.noSuchMethod(
            Invocation.method(#resetWithControl, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> requestControlOnly() =>
      (super.noSuchMethod(
            Invocation.method(#requestControlOnly, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<bool> supportsPowerControl() =>
      (super.noSuchMethod(
            Invocation.method(#supportsPowerControl, []),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> supportsResistanceControl() =>
      (super.noSuchMethod(
            Invocation.method(#supportsResistanceControl, []),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<_i19.SupportedResistanceLevelRange?>
  readSupportedResistanceLevelRange() =>
      (super.noSuchMethod(
            Invocation.method(#readSupportedResistanceLevelRange, []),
            returnValue:
                _i7.Future<_i19.SupportedResistanceLevelRange?>.value(),
          )
          as _i7.Future<_i19.SupportedResistanceLevelRange?>);

  @override
  _i7.Future<_i20.SupportedPowerRange?> readSupportedPowerRange() =>
      (super.noSuchMethod(
            Invocation.method(#readSupportedPowerRange, []),
            returnValue: _i7.Future<_i20.SupportedPowerRange?>.value(),
          )
          as _i7.Future<_i20.SupportedPowerRange?>);

  @override
  void updateDeviceType(_i17.DeviceType? deviceType) => super.noSuchMethod(
    Invocation.method(#updateDeviceType, [deviceType]),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<bool> connectToDevice(_i8.BluetoothDevice? device) =>
      (super.noSuchMethod(
            Invocation.method(#connectToDevice, [device]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i15.Widget? getDeviceIcon(_i15.BuildContext? context) =>
      (super.noSuchMethod(Invocation.method(#getDeviceIcon, [context]))
          as _i15.Widget?);

  @override
  bool isDeviceOfThisType(
    _i8.BluetoothDevice? device,
    List<_i8.ScanResult>? scanResults,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#isDeviceOfThisType, [device, scanResults]),
            returnValue: false,
          )
          as bool);

  @override
  _i7.Future<bool> isFtmsDevice(_i8.BluetoothDevice? device) =>
      (super.noSuchMethod(
            Invocation.method(#isFtmsDevice, [device]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> performConnection(_i8.BluetoothDevice? device) =>
      (super.noSuchMethod(
            Invocation.method(#performConnection, [device]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<void> performDisconnection(_i8.BluetoothDevice? device) =>
      (super.noSuchMethod(
            Invocation.method(#performDisconnection, [device]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i15.Widget? getDevicePage(_i8.BluetoothDevice? device) =>
      (super.noSuchMethod(Invocation.method(#getDevicePage, [device]))
          as _i15.Widget?);

  @override
  List<_i15.Widget> getConnectedActions(
    _i8.BluetoothDevice? device,
    _i15.BuildContext? context,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getConnectedActions, [device, context]),
            returnValue: <_i15.Widget>[],
          )
          as List<_i15.Widget>);

  @override
  _i7.Future<void> disconnectFromDevice(_i8.BluetoothDevice? device) =>
      (super.noSuchMethod(
            Invocation.method(#disconnectFromDevice, [device]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void setDeviceManager(_i21.SupportedBTDeviceManager? deviceManager) =>
      super.noSuchMethod(
        Invocation.method(#setDeviceManager, [deviceManager]),
        returnValueForMissingStub: null,
      );

  @override
  void notifyDevicesChanged() => super.noSuchMethod(
    Invocation.method(#notifyDevicesChanged, []),
    returnValueForMissingStub: null,
  );
}
