name: Build Multi-Platform

on:
  workflow_run:
    workflows: ["flutter_ci"]
    types:
      - completed
    branches: [ main ]
  push:
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  ARTIFACT_SUFFIX: ${{ github.ref_type == 'tag' && github.ref_name || (github.event_name == 'pull_request' && format('{0}-{1}', github.head_ref, github.event.number) || 'latest') }}

jobs:
  build-windows:
    runs-on: windows-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Cache Flutter SDK
      uses: actions/cache@v4
      with:
        path: |
          ${{ runner.tool_cache }}/flutter
        key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: |
          ${{ runner.os }}-flutter-
    
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'
        cache: true
        
    - name: Cache pub dependencies
      uses: actions/cache@v4
      with:
        path: |
          ${{ env.PUB_CACHE }}
          ~/.pub-cache
        key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: |
          ${{ runner.os }}-pub-
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Enable Windows desktop
      run: flutter config --enable-windows-desktop
      
    - name: Build Windows app
      run: flutter build windows --release
      
    - name: Upload Windows build
      uses: actions/upload-artifact@v4
      with:
        name: windows-build-${{ env.ARTIFACT_SUFFIX }}
        path: build/windows/x64/runner/Release/

  build-macos:
    runs-on: macos-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Cache Flutter SDK
      uses: actions/cache@v4
      with:
        path: |
          ${{ runner.tool_cache }}/flutter
        key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: |
          ${{ runner.os }}-flutter-
    
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'
        cache: true
        
    - name: Cache pub dependencies
      uses: actions/cache@v4
      with:
        path: |
          ${{ env.PUB_CACHE }}
          ~/.pub-cache
        key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: |
          ${{ runner.os }}-pub-
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Enable macOS desktop
      run: flutter config --enable-macos-desktop
      
    - name: Build macOS app
      run: flutter build macos --release
      
    - name: Create DMG (optional)
      run: |
        # Install create-dmg if you want to create a DMG installer
        # brew install create-dmg
        # create-dmg --volname "PowerTrain" --window-size 800 400 --icon-size 100 --app-drop-link 600 185 "PowerTrain.dmg" "build/macos/Build/Products/Release/"
        echo "macOS build completed"
      
    - name: Upload macOS build
      uses: actions/upload-artifact@v4
      with:
        name: macos-build-${{ env.ARTIFACT_SUFFIX }}
        path: build/macos/Build/Products/Release/

  build-android:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Cache Flutter SDK
      uses: actions/cache@v4
      with:
        path: |
          ${{ runner.tool_cache }}/flutter
        key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: |
          ${{ runner.os }}-flutter-
    
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'
        cache: true
        
    - name: Cache pub dependencies
      uses: actions/cache@v4
      with:
        path: |
          ${{ env.PUB_CACHE }}
          ~/.pub-cache
        key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: |
          ${{ runner.os }}-pub-
          
    - name: Cache Gradle dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Build Android APK
      run: flutter build apk --release
      
    - name: Build Android App Bundle
      run: flutter build appbundle --release
      
    - name: Upload Android APK
      uses: actions/upload-artifact@v4
      with:
        name: android-apk-${{ env.ARTIFACT_SUFFIX }}
        path: build/app/outputs/flutter-apk/app-release.apk
        
    - name: Upload Android App Bundle
      uses: actions/upload-artifact@v4
      with:
        name: android-aab-${{ env.ARTIFACT_SUFFIX }}
        path: build/app/outputs/bundle/release/app-release.aab

  build-web:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Cache Flutter SDK
      uses: actions/cache@v4
      with:
        path: |
          ${{ runner.tool_cache }}/flutter
        key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: |
          ${{ runner.os }}-flutter-
    
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'
        cache: true
        
    - name: Cache pub dependencies
      uses: actions/cache@v4
      with:
        path: |
          ${{ env.PUB_CACHE }}
          ~/.pub-cache
        key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: |
          ${{ runner.os }}-pub-
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Enable web
      run: flutter config --enable-web
      
    - name: Build Web app
      run: flutter build web --release
      
    - name: Upload Web build
      uses: actions/upload-artifact@v4
      with:
        name: web-build-${{ env.ARTIFACT_SUFFIX }}
        path: build/web/